### PR TITLE
New damping and stiffness to avoid sliding in Gazebo

### PR DESCRIPTION
**Pull request by miccol**
Adding Stiffness and damping parameters for the two tires seemed to have solved the problem of R1 sliding in gazebo..

### CODE REVIEW

**Comment by randaz81** [comment]
* Some values seem strange.
* Untested on the latest SW version. Behavior should be re-checked.

**Comment by vvasco** [comment]
Hi @miccol @randaz81 , I'm currently using this branch to avoid R1 sliding in `gazebo`. I rebased it on the last version of `master` and updated the damping and the stiffness of the sdf of `cer_320x240`

**Comment by pattacini** [comment]
Apparently, we cannot run our simulated experiments for FDG based on current `master`. So, merging this PR will make our life easier 😉 

Does any particular concern prevent merging?

**Comment by vvasco** [comment]
Btw, I'm using this branch and it works (I use `gazebo 11`).

**Comment by miccol** [comment]
> Hi @miccol @randaz81 , I'm currently using this branch to avoid R1 sliding in `gazebo`. I rebased it on the last version of `master` and updated the damping and the stiffness of the sdf of `cer_320x240`

Thanks @vvasco , I have no concern in merging this branch. But let's wait for @randaz81's green light

**Comment by randaz81** [comment]
Actually I never tested it Gazebo 11, and there are known problems on Gazebo 9.
Additionally, Gazebo 11 is uninstallable on a system with ROS melodic (last version of ubuntu 18.04) because of incompatible ubuntu packages. 
So I cannot merge it for now... 

PS: Please note that ROS  Noetic Ninjemys is expeceted to be released in May 2020. Maybe we need to wait just a couple of weeks more...

**Comment by pattacini** [comment]
Hi @randaz81 

Actually, the modifications @vvasco did are in this branch, and given that it is not merged I don't see why we should rename it.

**Comment by vvasco** [comment]
Hi @randaz81, let me clarify that the model `cer_320x240` in `master` only contains the modifications to the camera parameters. The changes to the ode parameters I made are only in this branch.

**Comment by randaz81** [comment]
ah ok, sorry, I misunderstood. Well in this case, I'd propose to wait a couple of weeks more. I'll keep you updated on the situation. I also want to switch to gazebo 11, and solve this issue ASAP!

Just for curiosity (and better alignment), are you already using Ubuntu 20 in your project?

**Comment by vvasco** [comment]
Nope, I'm using Ubuntu 18.04.

**Comment by pattacini** [comment]
Hi @randaz81 what's the current status of this?

**Comment by pattacini** [comment]
Gentle ping for @randaz81 on this.

**Comment by pattacini** [comment]
During our latest general meetup on SW, @randaz81 said that this problem should be now fixed up with Gazebo 11.
Thus, we could close this PR unmerged.

Before doing this, it might be worth giving a try to our TUG pipeline @vvasco.

**Comment by vvasco** [comment]
I confirm the robot does not slide in Gazebo 11.0 (tested on Ubuntu 18.04).
I also tested our TUG pipeline and it works.

@pattacini @randaz81 @miccol

**Comment by pattacini** [comment]
Thanks @vvasco for testing this!
@miccol I'll close this PR unmerged then!

**Pull request closed without merging**
